In [1]:
#import necessary Python packages
import os
import numpy as np
import urllib.request

#print message after packages imported succesfully
print("import of packages successful")

import of packages successful


In [2]:
os.getcwd()

'C:\\Users\\markb\\earth-analytics-bootcamp\\ea-bootcamp-day-4'

In [3]:
# set the working directory to the 'earth-analytics-bootcamp' directory
os.chdir("C:\\Users\\markb\\earth-analytics-bootcamp")

# print the current working directory
os.getcwd()

'C:\\Users\\markb\\earth-analytics-bootcamp'

In [6]:
# 'urlib' download files from Earth Lab figshare repository

# download .txt containing monthly average precipitation for Boulder, CO
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12565616",
                           filename = "data/avg-monthly-precip.txt")

# download .txt containing monthly names
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12565619",
                           filename = "data/months.txt")
                            

#print message that data downloads were successful
print("datasets downloaded successfully")


datasets downloaded successfully


In [9]:
# set the working directory to earth-analytics-bootcamp\\data

os.chdir("C:\\Users\\markb\\earth-analytics-bootcamp\\data")

In [10]:
#import the monthly average values from 'avg-monthly-precip.txt' as a numpy array

avg_monthly_precip = np.loadtxt(fname = "/users/markb/earth-analytics-bootcamp/data/avg-monthly-precip.txt")

#print the data in 'avg_monthly_precip'
print(avg_monthly_precip)


[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [11]:
#print the type of the 'avg_monthly_precip' variable
print(type(avg_monthly_precip))

<class 'numpy.ndarray'>


In [12]:
# import the names of the months from month.txt as a numpy array
months = np.genfromtxt("/users/markb/earth-analytics-bootcamp/data/months.txt", dtype='str')

# print the type for the 'months' variable
print(type(months))

# print the values in 'months'
print(months)



<class 'numpy.ndarray'>
['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June' 'July' 'Aug' 'Sept' 'Oct' 'Nov'
 'Dec']


In [16]:
#Optional Challenge
# set the working directory to the 'earth-analytics-bootcamp' directory
os.chdir("C:\\Users\\markb\\earth-analytics-bootcamp")

# download .csv containing monthly precip for Boulder, CO for 2002 and 2013
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12707792",
                           filename = "data/precip_2002_2013.csv")
                            

#print message that data downloads were successful
print("datasets downloaded successfully")

datasets downloaded successfully


In [17]:
# set the working directory to earth-analytics-bootcamp\\data
os.chdir("C:\\Users\\markb\\earth-analytics-bootcamp\\data")

In [22]:
# import the data from precip_2002_2013 as a numpy array
precip_2002_2013 = np.loadtxt(fname = "/users/markb/earth-analytics-bootcamp/data/precip_2002_2013.csv", delimiter=',')

# print the  data type for 'precip_2002_2013'
print(type(precip_2002_2013))

# display values as floats rather than scientific notation
np.set_printoptions(suppress=True)

# print the values in 'precip_2002_2013'
print(precip_2002_2013)

# print the values in avg_monthly_precip
print(avg_monthly_precip)

<class 'numpy.ndarray'>
[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]
[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]
